version: '3.8'

services:
  spring-app:
    container_name: haruni-server
    image: ${DOCKER_USERNAME}/haruni-server:latest
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul

  redis:
    container_name: redis-server
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge