spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  security:
    jwt:
      access-token:
        expired-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
      refresh-token:
        expired-time: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
      secret: ${JWT_SECRET}

model-server:
  url: ${MODEL_SERVER_URL}

firebase:
  config:
    path: firebase/firebase_service_key.json

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace