spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  security:
    jwt:
      access-token:
        expired-time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}
      refresh-token:
        expired-time: ${JWT_REFRESH_TOKEN_EXPIRED_TIME}
      secret: ${JWT_SECRET}

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-info-authentication-method: header
            user-name-attribute: response

          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-info-authentication-method: header
            user-name-attribute: id

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    keep-alive-timeout: 120000
  port: 8443

model-server:
  url: ${MODEL_SERVER_URL}

firebase:
  config:
    path: firebase/firebase_service_key.json

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info